### ISSUE TITLE
How to acquire the global accuracy of all swarm nodes?

### ISSUE THREAD

**Issue by yudshj** [schultzelab/swarm_learning#3]
I have reproduced your example scripts successfully, however, I still wonder how to acquire a global accuracy of all swarm nodes, which means merging the prediction results gathered from different swarm nodes. As I can see in the figure in your [nature paper](https://doi.org/10.1038/s41586-021-03583-3), the accuracy of the column "swarm" is higher than any swarm learning node, therefore, I wonder if you achieve this result by aggregating prediction probabilities of different nodes via soft voting or other algorithms. I really appreciate your help.

![image](https://user-images.githubusercontent.com/16971372/127136829-77a9ded5-2f18-4e52-a8e9-515a9eeb9682.png)

Thanks!

**Comment by CarolineCLJ** [comment]
你好，我想问一下，作者提供的代码是不是没有全局模型聚合这一部分？我没搞明白各个节点将训练的模型提交到SL网络后，是如何进行全局模型聚合的，还有作者提到的智能合约以及leader的选择又是如何操作的？如果你了解，可以大概的描述一下吗？谢谢！

**Comment by hanjialiang** [comment]
> 你好，我想问一下，作者提供的代码是不是没有全局模型聚合这一部分？我没搞明白各个节点将训练的模型提交到SL网络后，是如何进行全局模型聚合的，还有作者提到的智能合约以及leader的选择又是如何操作的？如果你了解，可以大概的描述一下吗？谢谢！

We have the same issue, and I suppose the authors of [the Nature paper](https://www.nature.com/articles/s41586-021-03583-3) have not provided the code of this part.

**Comment by SHerresthal** [comment]
Hi! In swarm learning, parameters from the single node models are merged using e.g. average (but other functions are in principle also possible), which results in the swarm model. So the accuracy of the swam model is not achieved by merging prediction results of nodes, but rather model parameters are merged. In the figure you mention, the accuracy of this swarm model is compared to the accuracy of models that were trained on single nodes only.
HPE is providing the Swarm Learning library (in binary format) for non-commercial use under evaluation license (see here: https://github.com/HewlettPackard/swarm-learning). The Swarm Learning code is not open sourced.
