### ISSUE TITLE
Model aggregation

### ISSUE THREAD

**Issue by CarolineCLJ** [schultzelab/swarm_learning#4]
Hi, what kind of smart contract is used for parameter aggregation using blockchain smart contract mentioned in the paper? Can you describe the process of dynamic leader selection in detail? thank you!

**Comment by SHerresthal** [comment]
Hi, it would be great if you could re-post that question in the swarm learning library repository run by HPE. Thanks! https://github.com/HewlettPackard/swarm-learning
